services:
  wb_manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wb_manager
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./${LOG_FOLDER}:/project/${LOG_FOLDER}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - dev_marketplace_network
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    stdin_open: true
    tty: true

networks:
  dev_marketplace_network:
    external: true
